### PR TITLE
Add extra schemas

### PR DESCRIPTION
**Pull request by michaelweiser**
Support import of additional schema files from puppet master and provide
one for RFC2307bis and groupOfEntries proposal.

### CODE REVIEW

**Comment by bilco105** [comment]
@michaelweiser I like the idea of users being able to include external schema files, but don't necessarily agree this is the right approach.

IMO schema files should be stored elsewhere (generally roles/profiles) and the define ldap::schema_file should take a path to where the file is, i.e.

```puppet
ldap::schema_file { "groupofentries":
  source => "puppet://path/to/groupofentries.schema",
}
```

**Comment by bilco105** [comment]
I also don't see how groupofentries or rfc2307bis are being included into LDAP currently, but either way, it should be the users responsibility to include whatever additional schemas they want.

**Comment by michaelweiser** [comment]
@bilco105: How about this then? The source is now fully configurable (but defaults to puppet:///files/ldap/schema) if the resource is used directly. If $extra_schemas of ldap::server is used, the source directory defaults to the same but can be configured using $ldap::server::schema_source_directory.
I'd like to retain the functionality of just specifying an array of schema names and have the module do the right thing...

**Comment by bilco105** [comment]
Looks great to me.. happy to merge once the tests pass.

Final question, should ldap::schema_file be notifying ldap::server::service? It feels like it should.

**Comment by michaelweiser** [comment]
Glad you ask because I thought about that, too. But then I remembered that nothing in config.pp does, most likely because server.pp already has
```
 class { '::ldap::server::config': } ~>
 class { '::ldap::server::service': }
```
which I guess takes care of that. I'm not familiar with this design pattern though and would have put an explicit notification on it out of reflex.

**Comment by bilco105** [comment]
Ah yes, you're right. If you can fix up the failing tests, I'll merge it.

**Comment by michaelweiser** [comment]
Mhmm, merged with current master and fixed the quoting issues. But now it says:
manifests/params.pp:46:puppet_url_without_modules:WARNING:puppet:// URL without modules/ found

What do we do now? Remove the default altogether or disable that lint check?

**Comment by bilco105** [comment]
Probably makes sense to remove the default, either that or set it as ```puppet:///modules/ldap/files/etc```

**Comment by michaelweiser** [comment]
Found this: https://github.com/rodjek/puppet-lint/issues/307. So it's not in the style guide and is going to move off into a plugin and be disabled by default in puppet lint. I vote for disabling the check because we chose that default for good reasons.

**Comment by bilco105** [comment]
Okay, sounds good to me. Merged

**Pull request merged**
