### PR TITLE
fix accentuated attributes comparison

### PR DESCRIPTION
**Pull request by maxdelorme**
Because I'm french my attributes in LDAP have some accent : ex Développeur for Developper
The current test of comparison was always wrong because the ldap are ASCII-8BIT string vs hiera which in UTF-8
So to compare attributes, I convert to string and then to UTF-8, by default the string from Openldap are ASCII-8BIT encoding

### CODE REVIEW

**Comment by yankcrime** [comment]
Looks reasonable to me - @seanhandley ?

**Comment by seanhandley** [comment]
@yankcrime Here's my concern:

```
irb(main):001:0> ['a','b'] == ['b','a']
=> false
irb(main):002:0> ['a','b'].sort == ['b','a'].sort
```

**Comment by seanhandley** [comment]
By using `#to_set`, we get a reliable concept of equality of sets. With array equality, the ordering of the contents matters.

If you did

```ruby
entry.send(k).sort.join(",").force_encoding('UTF-8') == [resource[:attributes][k]].flatten.sort.join(",")
```

then that'd work.

**Comment by maxdelorme** [comment]
I've changed it, thanks for the review.
Feel free to merge :-)

**Comment by seanhandley** [comment]
Thanks @maxdelorme :+1:

**Comment by maxdelorme** [comment]
Thanks

2015-06-04 14:38 GMT+02:00 Sean Handley <notifications@github.com>:

> Merged #55 <https://github.com/datacentred/datacentred-ldap/pull/55>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datacentred/datacentred-ldap/pull/55#event-322449894>.
>



-- 
-------------------------------------------------------------------------------------------------------
Maxime Delorme
Directeur du développement logiciel
4, rue du Faubourg Montmartre, 75009 Paris

Fixe :    +33 1 79 74 16 96
Mobile : +33 6 61 52 00 46
---------------------------------------------------------------------------------------------------------

-- 
Site @ : www.tennaxia.com

<http://www.tennaxia.com?signature=logo>
____________________________

  
<http://www.tennaxia.com/actualites/actualites-tennaxia/?signature=newsletter>  
<https://www.linkedin.com/company/tennaxia?signature=linkedin>   
<http://www.viadeo.com/fr/company/tennaxia?signature=viadeo>   
<https://twitter.com/Tennaxia?signature=twitter>   

*Adoptez l'éco-attitude. N'imprimez ce mail que si cela est vraiment 
nécessaire !*

**Pull request merged**
