### PR TITLE
config / monitor fixes and directory permissions

### PR DESCRIPTION
**Pull request by coreone**
I was trying to get this working on a RHEL6 VM and ran across a few problems.  This pull request:

* Fixes a permissions issue where the `$server_run_directory` was never setup to have the correct permissions for `$ldapowner` and `$ldapgroup`, so starting the service as a non-root user would fail.
* Setting `$configdn`, `$configpw`, `$monitordn`, and `$monitorpw` to the `$rootdn` and `$rootpw` values respectively did not work, so when monitor/config was turned on, the config would not allow slapd to start.  I moved this to `server/config.pp` and updated the template to use some new variables where, if config/monitor is enabled, but their dn/pw values are not set, then they will be set to the `root` values.
* Update the configs for config/monitor to not include `rootpw` and ACLs, since `rootpw` throws an error that causes slapd to not start, and the ACLs generate a warning as they are unneeded.
* Minor change to validate `$config` and `$monitor` as bool values in `server.pp`

### CODE REVIEW

**Comment by coreone** [comment]
Appended to this the ability to pass "sizelimit" and "timelimit" to ldap::server as options.  The defaults in params are the slapd default values.

**Comment by bilco105** [comment]
Hi @coreone 

Sorry for taking so long to get to this PR.

Could I possibly ask you to split this up into multiple PRs so we can address each point individually? - I've a couple of concerns about the code additions to ```ldap::server::config```, but don't want to block the other changes.

Thanks!

**Comment by coreone** [comment]
Added 3 separate pull requests for the pieces that I hope all work.  After I did it, I noticed that config settings depends on run directory, so as long as you approve the run directory PR first, that config one should be fine, even if we have to twiddle with it a bit.  I also added a third that is just the time/size limits.  Once all the config pieces are figured out, I will need to put in another PR against whatever is committed for those config changes, as 2-3 commits related to ACLs on monitor/config databases depend upon how that was finally configured.

Thanks!

**Comment by bilco105** [comment]
Ok to close this one @coreone ?

**Comment by coreone** [comment]
Feel free to close this one now.  The last bits regarding rootpw and config/monitor ACLs is now included in a separate PR.

Thanks!

**Pull request closed without merging**
